# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: eventiify_development_1
  pool: 5
  username: root
  password: root
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: eventiify_production_1
  pool: 5
  username: root
  password: root
  host: localhost  
